micronaut:
  application:
    name: pixGrpc

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:postgresql://localhost:5433/pix
    driverClassName: org.postgresql.Driver
    username: pix
    password: password
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: false
jpa.default.properties.hibernate.format_sql: false

itau:
  contas:
    url: 'http://localhost:9091'

bcb:
  pix:
    url: 'http://localhost:8082'